### ISSUE TITLE
Scatter plot: Packed categories with sparse columns

### ISSUE THREAD

**Issue by dionissqq** [datagrok-ai/public#1126]

**Comment by dionissqq** [comment]
Fixed in v1.7.2

**Comment by katerina-stepanova** [comment]
DG 1.8.2

Empty categories are still shown with 'pack and zoom by filter' option by default, if filter panel is hiddeb:
<img width="500" alt="image" src="https://user-images.githubusercontent.com/15780643/199710510-9efd8310-dee5-4c88-82f9-7ac96cc8bafe.png">
'Extra' categories are removed only on opening filter panel.

**Comment by dionissqq** [comment]
Thanks, I will fix this by the next meeting

**Comment by skalkin** [comment]
@dionissqq Why does it depend on the filter panel being open?

**Comment by katerina-stepanova** [comment]
More detailed steps:
1. Open SPGI
2. Find FaSSIF column and add 2 values: one for a row with 'Triazoles' in Series column, another one for a row with 'Pyrrolidines' in Series column (or used attached CSV with changes already made)
[SPGI (3).csv](https://github.com/datagrok-ai/public/files/9936789/SPGI.3.csv)
3. Add a scatter plot
4. Switch 'Zoom and filter' to 'pack and zoom by filter'
5. Select Series on Y axis
6. Select FaSSIF on X axis

**Comment by dionissqq** [comment]
Fixes in v1.8.3
