### ISSUE TITLE
Chem - Descriptors fail on sparse dataset

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#1674]
Most Chem augmentation functions (Chem | Descriptors and Chem | Map Identifiers) fail when a record lacks a Structure or potentially if the function returns nothing.

This is reproducible by loading the ‘sar-small.csv’ sample file and then by adding an empty row. Use the plus symbol at the bottom of the table. Then run any of the Descriptor functions or Map Identifiers functions. You will receive an error similar to “Row counts don’t match (data frame: 201, column: 150)”

I don’t believe this is expected behavior. If a row lacks a structure (or is invalid) then that row should be skipped and the entire operation should succeed. This will allow users to have sparsely populated compound datasets.

Similar to this issue is the generation of 'Chem | Fingerprints". The empty row should not produce a fingerprint but seems to with a value of “2048 bits, 0 set”.

**Comment by ahadzhanian** [comment]
See the ticket on Map Identifiers [here](https://github.com/datagrok-ai/public/issues/1495)

**Comment by ahadzhanian** [comment]
Fingerprints are fixed earlier. Can't reproduce on Chem v 1.5.10

**Comment by tcarolan** [comment]
Olena, confirming that the latest Chem 1.5.10 fixes the 'Chem | Descriptors' error. However, the 'Chem | Identifiers' error still persists. There is a separate ticket tracking that effort: https://github.com/datagrok-ai/public/issues/1495

**Comment by ahadzhanian** [comment]
> Olena, confirming that the latest Chem 1.5.10 fixes the 'Chem | Descriptors' error. However, the 'Chem | Identifiers' error still persists. There is a separate ticket tracking that effort: #1495

Tom, kindly thank you for your feedback! [#1495](https://github.com/datagrok-ai/public/issues/1495) ticket is in our high priority
