### ISSUE TITLE
Pinned columns are not displayed properly with some row source options for the table

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#2117]
**Steps to reproduce:** 
1. Open a table
2. Pin some columns
3. Select one of the following options for table's row source:
- Selected
- MouseOverRow
- MouseOverGroup
- FilteredSelected
- SelectedOrCurrent
4. Use another viewer to change which rows are displayed in the table (select somthing, filter, mouse over etc.)

**Expected results:** Pinned columns area display the same rows as the main part of the table.

**Actual results:** Pinned columns area is not updated properly.
'MouseOverGroup' option (pinned columns are not updated at all):
![2023-07-04_13-03-56 (1)](https://github.com/datagrok-ai/public/assets/15780643/18313f9b-f5f2-4229-8033-63029749f842)
'Selected' option (pinned columns are updated on click on the pinned columns area, otherwise previous selection is displayed):
![2023-07-04_13-05-50 (1)](https://github.com/datagrok-ai/public/assets/15780643/7af5ac70-95b5-4c6c-8a09-066a50f38426)

**Comment by dgosi** [comment]
The fix for mouse over issue is available in v 1.1.25 of PowerGrid package. Selection or filtering from other viewers cause pinned column to update accordingly. No issue was observed.

**Comment by ahadzhanian** [comment]
@dgosi Could you please specify the package version and let me know if there are any platform updates I need to wait for before testing? I'm still reproducing the bug on PowerGrid 1.1.25.


![Image](https://github.com/datagrok-ai/public/assets/111368431/6abdd041-fae7-41ee-afd5-fddd0d4f2ab0)

**Comment by dgosi** [comment]
I am using dev  server. Could you please describe the exact steps and the viewers to reproduce the issue? For me filtering, mouse over and selection do update pinned columns.

**Comment by ahadzhanian** [comment]
We can experience different behavior due to the operating system and browser differences. I use Windows 10, Chrome
To reproduce on dev: 

1. Open SPGI (I use Order and Hide columns to move the Chemist 521 column to the first position).
2. Add a grid viewer:
- Pin the Chemist 521 and ID columns
- Set Row Source to Selected, MouseOverGroup, CurrentRow
 3. Select rows in the initial grid.
 4. Add a pie chart, hover over its groups
 Actual result: the data in the pinned columns is not updated until you hover over the grid

![2117](https://github.com/datagrok-ai/public/assets/111368431/ffafbc1e-4370-4ac5-9194-6de2d5e45247)

**Comment by dgosi** [comment]
Thank you for providing the precise steps! MouseOverGroup and switching the rowSource property have been fixed. Everything else seems to work fine. All fixes are in v 1.1.27 of PowerGrid package.

**Comment by ahadzhanian** [comment]
I still reproduce a delay in updating pinned columns, when Row Source is set to:
- MouseOverRow
- FilteredSelected or Selected
- SelectedOrCurrent



![Image](https://github.com/datagrok-ai/public/assets/111368431/d9b3fdfd-0514-4873-afb6-10a6dd6f1998)
![Image](https://github.com/datagrok-ai/public/assets/111368431/b905367b-dd08-400b-ab07-31ba5e1177d3)
![Image](https://github.com/datagrok-ai/public/assets/111368431/eb3ca2dc-2a73-40c2-aea9-b66ac07773de)

**Comment by ahadzhanian** [comment]
PowerGrid 1.1.33

**Comment by ahadzhanian** [comment]
1. Add 2nd table to the page besides the default grid and pin a couple of columns in it
2. Configure this additional table to show FilteredSelected rows
3. Select multiple rows
4. Filter out some rows, so that additional table shows only 1-2 items
5. Reset filter

Expected: table with row source FilteredSelected is re-rendered on resetting filters
Actual: pinned columns area is re-rendered only when one of the table on the page is hovered.

**Comment by ahadzhanian** [comment]
Fixed in DG 1.17, PowerGrid 1.2.1
