### ISSUE TITLE
Filtering: 'Select columns' dialog for filter panel is showing currently selected columns incorrectly in some cases

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#320]
Reproduced on https://dev.datagrok.ai/

**1. Number of columns selected is shown incorrectly**
1. Open filters panel
2. Open 'Select columns' dialog through context/hamburger menu
**Expected results:** number of selected columns shown should be the same as number of checkboxes checked.
**Actual results:** "0 checked" in all cases:

**2. 'Select columns' dialog is initialised incorrectly when opened though properties panel**
1. Open filters panel
2. Close filters panel
3. Open it again 
4. Click the cog icon to open Properties panel
5. In Properties panel > Data click '...' near 'Column names' to open filters' 'Select columns' dialog
**Expected results:** Columns present currently in filters are shown as selected
**Actual results:** No columns are shown as selected.

**Comment by skalkin** [comment]
This has just been fixed in the latest code. @katerina-stepanova , the changes seem to be too big to be safely applied as a patch to the existing version (this is doable but will take more effort), would it be ok if the fix ships with the next major platform release? It seems to be a minor issue to me, assuming that the other (hamburger-driven) way still works

**Comment by katerina-stepanova** [comment]
Checked on https://dev.datagrok.ai/ (0.122.0)
Part 1: Number of columns selected is shown incorrectly - *can be still reproduce with the same steps*
Part 2: After the steps described the dialog itself has checkboxes now, but names of the columns are missing from properties panel:
![image](https://user-images.githubusercontent.com/15780643/153169490-5d4805b1-932e-4b56-91a3-923dc2e08f78.png)

**Comment by skalkin** [comment]
Yes, it won't show all column names/numbers in the properties panel under these specific circumstances, but column selection dialog works fine. Fixing it properly would require significant changes in the branch we are using, and it appears to be a very minor issue.
