### ISSUE TITLE
Chem: Structure filter (MarvinJS) cannot be removed from filter panel once added

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#535]
DG 0.150.1, CaMarvin 0.1.0, Chem 0.51.5, PowerPack 0.0.9

**Steps to reproduce**
1. Open a table containing some structure column
2. Open filters panel
3. Add structure column to filters panel
4. Click 'x' to remove it
**Expected results:** structure column filter should be removed on clicking 'x'
**Actual results:** structure column filter is not removed. Error:
```
error: NullError: method not found: 'endsWith' on null
js_primitives.dart:30 stackTrace: api/packages/published/files/Chem/0.51.5/DRqIPcXfaI16WFM2X2vAvgRPujDGLAgb/2/dist/package.js 14760:91  SubstructureFilter.get isFiltering
js/api/js-api-common.js?4627 1:148847                                                                 SubstructureFilter.detach
packages/d4/src/filters/filter_control.dart 138:5                                                     aLw.fj
packages/d4/src/widgets/widget.dart 138:11                                                            Object.eZ
packages/d4/src/widgets/widget.dart 67:5                                                              aLw.aK1
packages/d4/src/filters/filters_core.dart 116:7                                                       p4.LA
packages/d4/src/filters/filters_core.dart 353:46                                                      bEu.
packages/d4/src/ui.dart 278:65                                                                        fi4.
packages/d4/src/widgets/icons.dart 80:67                                                              bWC.
packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48                                             d17.
packages/$sdk/lib/async/zone.dart 1132:12                                                             aU8
packages/$sdk/lib/async/zone.dart 1012:12                                                             cZR.z7
packages/$sdk/lib/async/zone.dart 909:14                                                              cZR.G6
packages/$sdk/lib/async/zone.dart 936:23                                                              cZU.
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48                                     fka.
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16                                 Nu.JV
packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16                                  Object.FL
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14                                     fk8
packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14                                     HTMLElement.<fn>
```
5. Open 'Select columns' dialog for filters panel
6. Click 'None'
7. Click OK
**Expected results:** all filters are removed.
**Actual results:** filters are not removed if there was a structure filter among them.

**Comment by RobertStrulak** [comment]
@skalkin - on priority

**Comment by skalkin** [comment]
Fixed in the latest Chem package.

**Comment by katerina-stepanova** [comment]
DG 1.1.5, chem 0.51.10
Issue is still reproduced in specific case for MarvinJS:
1. To make sure MarvinJS is default sketcher:
-Add a structure column to filters panel
-Open sketcher
-Switch to MarvinJS and close
2. Add another structure column to filters panel
3. Open sketcher (MarvinJS)
4. Close sketcher without drawing anything
5. Try to remove structure column from filters panel

**Expected results:** column should be removed.
**Actual results:** column is not removed, exception in console:

    stackTrace: api/packages/published/files/Chem/0.51.10/DpHdupPHlOzlsjEEHDACB9molRUHdsC5/1/dist/package.js 15163:91  get isFiltering
    js/api/js-api-common.js?67064 1:154136                                                                 SubstructureFilter.detach
    api/packages/published/files/Chem/0.51.10/DpHdupPHlOzlsjEEHDACB9molRUHdsC5/1/dist/package.js 15192:15  SubstructureFilter.detach
    packages/d4/src/filters/filter_control.dart 138:5                                                      aLK.fn
    packages/d4/src/widgets/widget.dart 138:11                                                             Object.f7
    packages/d4/src/widgets/widget.dart 67:5                                                               aLK.aKg
    packages/d4/src/filters/filters_core.dart 116:7                                                        p6.LG
    packages/d4/src/filters/filters_core.dart 353:46                                                       bEY.
    packages/d4/src/ui.dart 278:65                                                                         fjr.
    packages/d4/src/widgets/icons.dart 80:67                                                               bXb.
    packages/$sdk/lib/html/dart2js/html_dart2js.dart 42920:48                                              d1H.
    packages/$sdk/lib/async/zone.dart 1132:12                                                              aUo
    packages/$sdk/lib/async/zone.dart 1012:12                                                              d.q.zd
    packages/$sdk/lib/async/zone.dart 909:14                                                               d.q.Gc
    packages/$sdk/lib/async/zone.dart 936:23                                                               d.t.
    packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:48                                      flF.
    packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 474:16                                  ND.K.
    packages/$sdk/lib/_internal/js_runtime/lib/isolate_helper.dart 59:16                                   Object.FL
    packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2456:14                                      flD
    packages/$sdk/lib/_internal/js_runtime/lib/js_helper.dart 2476:14                                      HTMLElement.<fn>
