### ISSUE TITLE
Filter panel is not synchronised across different views

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#709]
**Steps to reproduce**
1. open a table (e.g. SPGI dataset)
2. Clone view
3. Open filters panel and filter out some values on the original view
4. Go to the cloned view and open filters panel

**Expected results:** Both views are filtered, filters panel is showing actual filters state in both views.
**Actual results:** Both views are filtered, but filter panel on the cloned view has all checkboxes selected:
<img width="937" alt="image" src="https://user-images.githubusercontent.com/15780643/174551803-eef8f2d0-154a-49be-aff9-98be5a40a3cc.png">

**Comment by skalkin** [comment]
Thanks for reporting! This is fixed in `Datagrok 1.4.2`.

**Comment by skalkin** [comment]
Apologies for closing it earlier - I think I meant to close another ticket and had two tabs open. Anyway, this issue has been addressed in `Datagrok 1.4.3`, which is building at the moment but will be available on https://devdatagrok.ai soon.

**Comment by katerina-stepanova** [comment]
@skalkin Filters are not synchronised in some cases when a column is added to filters panel:

Case 1: numerical filters
1. Open a table
3. Add another view for the same table (e.g. clone layout)
4. Open filters panel
5. Add a numerical column to filters
6. Set some filtering
7. Switch to another view
8. Add the same column to filters panel
**Expected:** the same filter range is set as on another view, table is filtered.
**Actual:** no filter range is selected, table filtering on this column is reset in both views.

Case 2: categorical filters
1. Open a table
3. Add another view for the same table (e.g. clone layout)
4. Open filters panel
5. Add a categorical column to filters
6. Set some filtering
7. Switch to another view
8. Add the same column to filters panel
**Expected:** checkboxes are synchronised with another view, table is filtered.
**Actual:** table is filtered, but all checkboxes are shown as selected.
Layout can be saved and re-applied in this state: table filtered, but no checkboxes shown as unchecked in respective filter.

**Comment by katerina-stepanova** [comment]
v1.6.11
Issues from comment above can be still reproduced.

And there is one more case:
Steps:
1. open filters > apply something > close/reopen filters > reset > clone view (View can be cloned from top menu View > Layout > Clone)
2. Apply some filter in the cloned view (can be either the same filter or another one)
3. Close filters panel in the cloned view
Expected results: Filters are un-applied when filters panel is closed.
Actual results: Filters are not unapplied when filters panel is closed in cloned view.

**Comment by onuf** [comment]
@skalkin checked the case from the above comment, still reproduced on dev `v1.8.1`

**Comment by skalkin** [comment]
@dionissqq Did you fix it recently? If yes, let's close it (and then our QA should test it)

**Comment by dionissqq** [comment]
Fixed in v1.8.3

**Comment by katerina-stepanova** [comment]
DG 1.8.3
Filters are reset on closing a tab/view with opened filter panel
To reproduce:
1. Open 2 views with filters opened on each of them
2. Filter something > filter panel states are synced on 2 views
3. Close one of the views

When view is closed, filters are reset though filter panel is still opened in the remaining view.
